### ISSUE TITLE
Make greentea standalone

### ISSUE THREAD

**Issue by Patater** [ARMmbed/greentea-client#18]
We'd like to make greentea standalone again, rather than part of the Mbed OS mono repo. Let's re-use the greentea-client repo, make a new branch that is up-to-date with the latest greentea from Mbed OS, and get the project into a good standalone shape.

- [x] Use this greentea-client repo
- [x] Update this repo with code from the latest version of mbed-os (#19) @LDong-Arm 
- [x] Add empty implementation of greentea_metrics (#20) @rwalton-arm 
- [x] Remove mbed_trace dependency (#20) @rwalton-arm 
- [x] Remove references to Mbed from code/comments (#23) @rajkan01
- [x] Refactor Greentea client folder structure according to [modern CMake](https://cliutils.gitlab.io/modern-cmake/) #21 @LDong-Arm 
- [x] Remove yotta references and files (including from README) (#23) @rajkan01
- [x] Document how to consume greentea-client using CMake (#24) @LDong-Arm 
- [x] Ensure no Mbed tests in greentea-client (leave those in Mbed OS) @rajkan01
- [x] Set up PR testing for greentea-client (GitHub Actions) @rwalton-arm (#22)
- [x] Replace Mbed serial with stdlib putc and puts (via default implementation of interface functions e.g. `greentea_putc()`) (#21) @LDong-Arm 
- [x] Remove dependency on greentea metrics reporting fixture from greentea-client  @rwalton-arm 
- [x] Fetch greentea-client using FetchContent from mbed-os repo (extern/) @Patater
- [X] Export CMake targets so consumers can use find_package or add_subdirectory @rwalton-arm 
- [x] ~Integration test and auto-update greentea-client within mbed-os~
- [X] Refactor Mbed OS's tests to use standalone version of greentea-client (when using CLI 2) @Patater
- [x] Document how to use ~standalone~ greentea-client API @LDong-Arm (#30)
- [X] ~Update Mbed documentation on how to produce the equivalent of greentea metrics (or remove docs if deprecating)~ Moved to https://github.com/ARMmbed/mbed-os/issues/14790
- [X] Set up code coverage @rwalton-arm #32 
- [x] Add unit tests @rwalton-arm #32 
- [x] Add static analysis @Patater #33
- [x] Update README to remove GREENTEA_CLIENT_STDIO option, and explain how to link with libraries instead (#35) @LDong-Arm
- [x] Use greentea-client from Mbed OS using FetchContent @Patater https://github.com/ARMmbed/mbed-os/pull/14803
- [x] Refactor mbed-os' existing greentea io so it can be used by greentea-client https://github.com/ARMmbed/mbed-os/issues/14893

**Comment by LDong-Arm** [comment]
All tasks on the list are done. A separate issue https://github.com/ARMmbed/mbed-os/issues/14790 exists for deprecated metrics from the in-tree greentea-client used by Mbed CLI 1.
